import { test, expect } from '@playwright/test';

/**
 * E2E for the editable-PPT (dashi) preview + download path.
 *
 * global-setup.ts generates a 2-page deck from the Chinese title
 * "量子计算前沿". The `_slugify_segment` fix maps it to the deterministic
 * ASCII dir `deck-82f50188`, so all URLs below are copy-safe ASCII. These
 * tests fail if the slug regresses (Chinese leaks into the path -> 404) or
 * if preview/download serving breaks.
 */

const BACKEND = 'http://localhost:8787';
const DECK = 'deck-82f50188';
const PREVIEW = `output/${DECK}/ppt/index.html`;
const PPTX = `output/${DECK}/ppt/${DECK}.pptx`;

// ─── Preview HTML ────────────────────────────────────────────────────────────

test('preview serves the slugged deck with injected <base> and slides', async ({ page }) => {
  const resp = await page.goto(`${BACKEND}/preview?path=${PREVIEW}`);
  expect(resp?.status()).toBe(200);

  const baseHref = await page.evaluate(
    () => document.querySelector('base')?.getAttribute('href') || null,
  );
  expect(baseHref).toBe(`/preview-static/output/${DECK}/ppt/`);
  // slug fix: nothing non-ASCII may leak into the asset base
  expect(baseHref!).toMatch(/^[\x00-\x7F]+$/);

  const slideCount = await page.evaluate(
    () => document.querySelectorAll('[class*="slide"], section, [data-slide]').length,
  );
  expect(slideCount).toBeGreaterThan(0);
});

// ─── PPTX download ───────────────────────────────────────────────────────────

test('download by path returns a valid PPTX (ZIP magic PK)', async ({ request }) => {
  const resp = await request.get(`${BACKEND}/download?path=${PPTX}`);
  expect(resp.status()).toBe(200);
  const body = await resp.body();
  expect(body.length).toBeGreaterThan(10000);
  expect(body[0]).toBe(0x50); // P
  expect(body[1]).toBe(0x4b); // K
});

test('download of the workspace copy (uploads) returns the same PPTX', async ({ request }) => {
  const resp = await request.get(`${BACKEND}/download?user_id=default_user&file=${DECK}.pptx`);
  expect(resp.status()).toBe(200);
  const body = await resp.body();
  expect(body.length).toBeGreaterThan(10000);
  expect(body[0]).toBe(0x50);
  expect(body[1]).toBe(0x4b);
});

// ─── File sidebar endpoints (list / delete) ──────────────────────────────────
// /decks now sources uploads/<user_id>; the generated pptx copy lands there and
// gets a preview_path because a matching output/<stem>/ppt/index.html exists.

const FILE = `${DECK}.pptx`;

test('GET /decks lists the uploads file with a usable preview_path', async ({ request }) => {
  const resp = await request.get(`${BACKEND}/decks?user_id=default_user`);
  expect(resp.status()).toBe(200);
  const { decks } = await resp.json();
  const d = decks.find((x: { name: string }) => x.name === FILE);
  expect(d, `file ${FILE} should be listed`).toBeTruthy();
  expect(d.preview_path).toBe(PREVIEW);
  expect(d.size).toBeGreaterThan(10000);
  // the paths the sidebar hands to /preview and /download must actually serve
  expect((await request.get(`${BACKEND}/preview?path=${d.preview_path}`)).status()).toBe(200);
  expect((await request.get(`${BACKEND}/download?user_id=default_user&file=${d.name}`)).status()).toBe(200);
});

test('DELETE /decks rejects traversal and empty names', async ({ request }) => {
  expect((await request.delete(`${BACKEND}/decks?name=${encodeURIComponent('../../etc')}`)).status()).toBe(400);
  expect((await request.delete(`${BACKEND}/decks`)).status()).toBe(400);
  expect((await request.delete(`${BACKEND}/decks?name=does-not-exist-xyz.pptx`)).status()).toBe(404);
});

test('DELETE single upload leaves other files intact (no whole-dir wipe)', async ({ request }) => {
  // upload two throwaway files, delete one, assert the other survives
  const mk = (name: string) =>
    request.post(`${BACKEND}/upload`, {
      multipart: { user_id: 'default_user', file: { name, mimeType: 'text/plain', buffer: Buffer.from('x') } },
    });
  await mk('e2e_a.txt');
  await mk('e2e_b.txt');
  expect((await request.delete(`${BACKEND}/uploads?user_id=default_user&file=e2e_a.txt`)).status()).toBe(200);
  const { decks } = await (await request.get(`${BACKEND}/decks?user_id=default_user`)).json();
  const names = decks.map((x: { name: string }) => x.name);
  expect(names).not.toContain('e2e_a.txt');
  expect(names).toContain('e2e_b.txt');
  await request.delete(`${BACKEND}/uploads?user_id=default_user&file=e2e_b.txt`);
});

test('DELETE /decks removes the file and its generated deck end-to-end', async ({ request }) => {
  // fixture deck-82f50188 is regenerated by global-setup on every run, so
  // deleting it proves the full list -> delete -> gone round-trip.
  expect((await request.delete(`${BACKEND}/decks?name=${FILE}&user_id=default_user`)).status()).toBe(200);
  const { decks } = await (await request.get(`${BACKEND}/decks?user_id=default_user`)).json();
  expect(decks.some((x: { name: string }) => x.name === FILE)).toBe(false);
  // its deck dir (preview source) is gone too -> preview 404s
  expect((await request.get(`${BACKEND}/preview?path=${PREVIEW}`)).status()).toBe(404);
});
